### ISSUE TITLE
"Bad Request" when associating two records for N:N relationship

### ISSUE THREAD

**Issue by WestJackson** [jlattimer/CRMRESTBuilder#1]
I am trying to associate two types of records -- a conference and a market sector. I have created an N:N relationship between them and am using the CRM REST Builder to associate the two records given their ID #'s. I have checked the ID's and made sure they are correct & that the relationship doesn't already exist.

Here is a screenshot of what I setup within CRM:
![crm rest bad request](https://cloud.githubusercontent.com/assets/6888169/19942012/811987c4-a0ef-11e6-9889-d5b25c89831a.png)

This results in "Bad Request" and that is it. I read through your updates and it seems like there shouldn't be any issues with association?

Any guidance would be appreciated. Not sure if it just won't work or if I need to do something differently.

Here is the code if you would rather have that:
```
var association = {'@odata.id': Xrm.Page.context.getClientUrl() + "/api/data/v8.0/ene_conferences(5B328BD3-24A1-E611-80F4-5065F38A4B81)"};
var req = new XMLHttpRequest();
req.open("POST", Xrm.Page.context.getClientUrl() + "/api/data/v8.0/ics_marketsectors(365303DE-077D-E511-8102-FC15B428ABA4)/ene_ene_conference_ics_marketsector/$ref", true);
req.setRequestHeader("Accept", "application/json");
req.setRequestHeader("Content-Type", "application/json; charset=utf-8");
req.setRequestHeader("OData-MaxVersion", "4.0");
req.setRequestHeader("OData-Version", "4.0");
req.onreadystatechange = function () {
    if (this.readyState === 4) {
        req.onreadystatechange = null;
        if (this.status === 204 || this.status === 1223) {
            //Success - No Return Data - Do Something
        }
        else {
            alert(this.statusText);
        }
    }
};
req.send(JSON.stringify(association));
```
Thanks for the great application. Been very useful recently.

**Comment by jlattimer** [comment]
Is it possible to use Fiddler or something else to look at the detail of the 400 response and post them here?

**Comment by SimonTrejtnar** [comment]
I am facing the same problem when trying to add products to entitlements:

code:
var association = {
    "@odata.id": Xrm.Page.context.getClientUrl() + "/api/data/v8.2/products(5bcfcbfa-8035-e711-8126-e0071b65dee1)"
};
var req = new XMLHttpRequest();
req.open("POST", Xrm.Page.context.getClientUrl() + "/api/data/v8.2/entitlements(02f4c672-1446-e711-811d-e0071b658eb1)/product_entitlement_association/$ref", true);
req.setRequestHeader("Accept", "application/json");
req.setRequestHeader("Content-Type", "application/json; charset=utf-8");
req.setRequestHeader("OData-MaxVersion", "4.0");
req.setRequestHeader("OData-Version", "4.0");
req.onreadystatechange = function() {
    if (this.readyState === 4) {
        req.onreadystatechange = null;
        if (this.status === 204 || this.status === 1223) {
            //Success - No Return Data - Do Something
        } else {
            Xrm.Utility.alertDialog(this.statusText);
        }
    }
};
req.send(JSON.stringify(association));



my request:
Request URL:https://uowcrmdev.crm4.dynamics.com/api/data/v8.2/entitlements(01f4c672-1446-e711-811d-e0071b658eb1)/product_entitlement_association/$ref
Request Method:POST
Status Code:400 Bad Request
Remote Address:13.106.110.54:443
Referrer Policy:no-referrer-when-downgrade

and payload:
@odata.id:"https://uowcrmdev.crm4.dynamics.com/api/data/v8.2/products(5bcfcbfa-8035-e711-8126-e0071b65dee1)"

Guids are correct and checked


to expand on the bad request, the response is:

"code":"","message":"Invalid role specified for entity 'entitlement'in relationship 'product_entitlement_association.Referencing'","innererror":{
      "message":"Invalid role specified for entity 'entitlement'in relationship 'product_entitlement_association.Referencing'","type":"System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]","stacktrace":"   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Associate(EntityReference entityReference, Relationship relationship, EntityReferenceCollection relatedEntities, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Associate(EntityReference entityReference, Relationship relationship, EntityReferenceCollection relatedEntities)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.UpdateResourceNavigationPropertyReference(CrmODataExecutionContext context, String edmEntityName, String entityKeyValue, String navigationPropertyName, CrmEdmEntityReference edmPropertyReference)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.UpdateNavigationRefInternal(String entityName, String key, String navigation, Uri link)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.PostNavigationRef(String entityName, String key, String navigation, Uri link)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"

**Comment by SimonTrejtnar** [comment]
also the metadata for the relationship as returned from web API:
"Entity1LogicalName":"product","Entity2LogicalName":"entitlement","IntersectEntityName":"entitlementproducts","Entity1IntersectAttribute":"productid","Entity2IntersectAttribute":"entitlementid","Entity1NavigationPropertyName":"product_entitlement_association","Entity2NavigationPropertyName":"product_entitlement_association","IsCustomRelationship":false,"IsCustomizable":{
        "Value":false,"CanBeChanged":false,"ManagedPropertyLogicalName":"iscustomizable"
      },"IsValidForAdvancedFind":true,"SchemaName":"product_entitlement_association","SecurityTypes":"None","IsManaged":true,"RelationshipType":"ManyToManyRelationship","IntroducedVersion":"6.1.0.0","MetadataId":"2f6bde36-f5a7-e211-90dd-00155d2c1704","HasChanged":null
    },{
      "Entity1AssociatedMenuConfiguration":{
        "Behavior":"DoNotDisplay","Group":"Details","Label":{
          "LocalizedLabels":[
            
          ],"UserLocalizedLabel":null
        },"Order":null
      },"Entity2AssociatedMenuConfiguration":{
        "Behavior":"DoNotDisplay","Group":"Details","Label":{
          "LocalizedLabels":[
            
          ],"UserLocalizedLabel":null
        },"Order":null

**Comment by SimonTrejtnar** [comment]
I changed the request and it worked:

I changed swapped the parent and child as below:

var association = {
                                            //"@odata.id": Xrm.Page.context.getClientUrl() + "/api/data/v8.2/products("+ productid +")"
                                            "@odata.id": Xrm.Page.context.getClientUrl() + "/api/data/v8.2/entitlements(" + result["entitlementid"] + ")"
                                        };
                                        var req3 = new XMLHttpRequest();
                                        //req3.open("POST", Xrm.Page.context.getClientUrl() + "/api/data/v8.2/entitlements(" + result["entitlementid"] + ")/product_entitlement_association/$ref", true);
                                        req3.open("POST", Xrm.Page.context.getClientUrl() + "/api/data/v8.2/products(" + productid + ")/product_entitlement_association/$ref", true);
                                        req3.setRequestHeader("Accept", "application/json");
                                        req3.setRequestHeader("Content-Type", "application/json; charset=utf-8");
                                        req3.setRequestHeader("OData-MaxVersion", "4.0");
                                        req3.setRequestHeader("OData-Version", "4.0");
                                        req3.onreadystatechange = function () {
                                            if (this.readyState === 4) {
                                                req3.onreadystatechange = null;
                                                if (this.status === 204 || this.status === 1223) {
                                                    //Success - No Return Data - Do Something
                                                } else {
                                                    Xrm.Utility.alertDialog(this.statusText);
                                                }
                                            }
                                        };
                                        req3.send(JSON.stringify(association));

**Comment by jlattimer** [comment]
Yeah - there are instances were it comes out backwards I'm afraid :(
