### ISSUE TITLE
Unable to filter using related records on Web API

### ISSUE THREAD

**Issue by ferodom** [jlattimer/CRMRESTBuilder#10]
According to the release notes on 2.4
Added Web API filtering on related records 

However for me the filter only allows me to select the original entity. I am using a custom entity and v8.1

**Comment by jlattimer** [comment]
Guess I didn't finish that :) I'll have to work on that for the next release

**Comment by ferodom** [comment]
Actually I read that it is only possible for a retrieve not a retrieve multiple. So perhaps that is what I missed, I tried just editing the query and pasting it on the browser and I got an error that you could not add a filter to an entityset

**Comment by jlattimer** [comment]
That's probably it - starts to get confusing after awhile as to what is supposed to work and what doesn't. Going to close this out for now.
