### ISSUE TITLE
Problem generating metadata for PluginTraceLog entity

### ISSUE THREAD

**Issue by Corzi** [jlattimer/CRMRESTBuilder#14]
When I select the PluginTraceLog Entity, the page hangs.

![image](https://cloud.githubusercontent.com/assets/1381855/23090823/10bdbe5a-f59f-11e6-886c-b62961fa02ea.png)

My console shows:

![image](https://cloud.githubusercontent.com/assets/1381855/23090830/38fdebb0-f59f-11e6-9df8-91198332085f.png)

**Comment by jlattimer** [comment]
Fixed
