### ISSUE TITLE
How to use it??

### ISSUE THREAD

**Issue by Heysoulnat88** [jlattimer/CRMRESTBuilder#15]
So I download the CRMRESTBuilder, also downloaded the CRMRESTBuilder_2_5_0_0_managed.
How can I use this?? should I import the CRMRESTBuilder_2_5_0_0_managed to the CRMRESTBuilder?? because every time I ran the program I only get it. It dosen't work

![image](https://cloud.githubusercontent.com/assets/26007085/23557009/85697a34-fffc-11e6-84da-20c2d2073d80.png)

**Comment by jlattimer** [comment]
If you navigate to the Solutions page - there will be button at the top to launch

![image](https://cloud.githubusercontent.com/assets/1769982/23557430/afe2a0a8-fff5-11e6-82d6-8ed7c49a041a.png)

**Comment by Heysoulnat88** [comment]
how to do that?

**Comment by jlattimer** [comment]
Did you install the solution zip into CRM? Navigate to Settings -> Solutions -> Import choose the zip file you downloaded and walk through the import

**Comment by Heysoulnat88** [comment]
CRMRESTBuilder_2_5_0_0_managed. I will Install it to the CRM right?

**Comment by Heysoulnat88** [comment]
or this CRMRESTBuilder?
