### ISSUE TITLE
 Referenced file '../../ClientGlobalContext.js.aspx' not found

### ISSUE THREAD

**Issue by pazure365** [jlattimer/CRMRESTBuilder#16]
Using Visual Studio against current code

       _Referenced file '../../ClientGlobalContext.js.aspx' not found_

Is that file available somewhere?

**Comment by jlattimer** [comment]
ClientGlobalContext.js.aspx is located in CRM and is loaded when you open the web resource

**Comment by pazure365** [comment]
Thanks! (Closing.)
