### ISSUE TITLE
Unable to load the page

### ISSUE THREAD

**Issue by Srini20in** [jlattimer/CRMRESTBuilder#18]
Hi Jason,
I installed the latest CRMRESTBuilder_2_5_0_0_managed on CRM online 2016 (8.2) version. It just keep spinning and not loading the content. Can you please share work around or any other alternatives? I don't see any error message to trouble shoot.
Just observed that it loads fine in Chrome so there may be some security thing that is preventing this.

![crm-restbuilder](https://cloud.githubusercontent.com/assets/20647813/26423873/4d6543ca-409d-11e7-997e-2a517317aba8.png)

**Comment by jlattimer** [comment]
In the browser can you hit F12 and then switch to the Console tab and see if there any errors?

**Comment by jlattimer** [comment]
Closed - no response
