### ISSUE TITLE
Unable to import the solution on Dynamics 365 8.2

### ISSUE THREAD

**Issue by kip-dk** [jlattimer/CRMRESTBuilder#19]
Hi

trying to import the solution into a clean 365 8.2 but gets the error ""you can only import the solution with a package version 8.2 or earlier into this organization.

Would it be possible for you to create a version of the solution file that allow import into Dynamics 365 version 8.2.

**Comment by jlattimer** [comment]
Are you using the 2.5.x version? It was exported from a 7.x environment and does work with D365 8.2

**Comment by kip-dk** [comment]
Yes, i downloaded to 2.5.0.0 version,

But tried downloading it again, and now it works, you can close the issue.

Tnx. for taking time to look into this. I really appriciate.



Regards
Kjeld

Mvh.
Kjeld Poulsen

Mail: kip@kipon.dk
Phone: +45 30 70 11 48
Web: http://kipon.dk
IN: https://www.linkedin.com/in/kipon

2017-05-30 15:01 GMT+02:00 Jason Lattimer <notifications@github.com>:
