### ISSUE TITLE
Missing Download of Managed Solution

### ISSUE THREAD

**Issue by justinwkruse** [jlattimer/CRMRESTBuilder#2]
Hello, I am not able to see / download the Managed Solution .zip file.  I checked on CodePlex and was not able to locate the file there either.

Thanks for your help.

**Comment by jlattimer** [comment]
Under releases there should be the 2.x & 1.x versions - each should have the managed zip under downloads

https://github.com/jlattimer/CRMRESTBuilder/releases

**Comment by justinwkruse** [comment]
Thanks for the help.
