### ISSUE TITLE
Cannot Open the Tool, Just Hangs With "Please wait..."

### ISSUE THREAD

**Issue by bdbvb** [jlattimer/CRMRESTBuilder#20]
I'm on CRM 2016 (web api 8.1). I'm using Chrome and IE (works on neither one). I'm not accessing directly on the server.

Unfortunately, it renders the product completely unusable.

Is there a workaround? Can I default to Web API? Do I need to configure some endpoint on the CRM server to satisfy the tool?

![image](https://user-images.githubusercontent.com/11095196/26843429-2d813264-4abe-11e7-9579-124623c6acc6.png)

**Comment by bdbvb** [comment]
The error in the console was related to a cross-site scripting issue.

At first I thought it might be related to the fact that I'm using https (and indeed I saw a bunch of mixed content messages, which makes me think the product doesn't play nice with https, though that's not the issue at hand).

Then I noticed that the URLs the product uses do not use the fully qualified host name. In my CRM developmnent environment I'm using something along the lines of https://myserver.mydomain.local:4444/MyOrganization/main.aspx., but the product is only using "myserver" for the host name.

I worked around this by utilizing just the server name (in my case, this meant using a different machine, though I guess you could also tweak your DNS settings). 

So, the main issue I think is that the product doesn't respect the full host name being used by CRM, and possibly also may have some issues using https.

So, I think there is a workaround, though the issues themselves are outstanding.

Thanks!

**Comment by jlattimer** [comment]
Uses whatever the getClientUrl returns for the address. So generally the problem lies in the server setup - CRM web resources don't often play nice unless you're using a FQDN.  This isn't something I'd be able to fix really as I'd have no way to convert the server name to a full qualified name.

**Comment by jlattimer** [comment]
Uses whatever the getClientUrl returns for the address. So generally the
problem lies in the server setup - CRM web resources don't often play nice
unless you're using a FQDN.  This isn't something I'd be able to fix really
as I'd have no way to convert the server name to a full qualified name.

-> Jason Lattimer
