### ISSUE TITLE
Texting in operator selector is wrong

### ISSUE THREAD

**Issue by kip-dk** [jlattimer/CRMRESTBuilder#21]
When selecting condition, the le operator is named "Is greter than.."  it does generate the le operator, so i assume it is a simple copy paste error.

![image](https://user-images.githubusercontent.com/8783399/26962901-b1bb4c54-4ce9-11e7-9388-96d4ba9478ea.png)

**Comment by jlattimer** [comment]
Thanks for pointing that out. Next time I get in and do a release I'll get this updated.
