### ISSUE TITLE
Suggestion : feature enhancements

### ISSUE THREAD

**Issue by VenkattaPidikiti** [jlattimer/CRMRESTBuilder#22]
Hi Jlattimer,

I am playing with tool from last couple of days whilst  I have observed ,if tool have below features it would be good.

1. Select all attributes for Create ,Update ( expect internal system fields) : Reason: assume a scenario where we have more than 250 attributes at a form to generate a REST point and it will take nearly 4-5 hours of routine add attribute efforts..
2. User friendly error message and return message for all Operations.
3. Additionally tool generate requests as per below MSDN URL:
https://msdn.microsoft.com/en-us/library/gg328090.aspx

Venkatta

**Comment by jlattimer** [comment]
If you are trying to get all the attributes (which should be very rarely) - just don't select any and it will return them all.

**Comment by butsify** [comment]
hi, i thought "feature enhancements" is the right place for this question: are you planning to move the builder to the xrmtoolbox in the future?

**Comment by jlattimer** [comment]
I'm considering it for the re-write I was planning on doing when v9 comes out - a Web API only version.
