### ISSUE TITLE
CRM Rest builder not supported in latest build Version 1612 (8.2.1.176)?

### ISSUE THREAD

**Issue by deepthi261** [jlattimer/CRMRESTBuilder#23]
noticed after updating to u2 that CRM Rest Builder, is showing loading (way too long) & doesn't open. Is this a known issue?

**Comment by jlattimer** [comment]
Which browser? If Chrome, do you have the Level Up extension installed?

**Comment by deepthi261** [comment]
I checked in both browsers - IE 11 & Chrome , Yes level Up extension installed in chrome

**Comment by jlattimer** [comment]
It should work in IE - it's not the version of CRM that is the problem. The Level Up extension just recently changed the way it loads its scripts - which now causes a conflict with my tool I've contacted the author and I believe he'll be making an update to rectify this.

**Comment by deepthi261** [comment]
Nope Sir Checked again, its not working for me in IE - just showing loading page but not opening! 
doubt  -> Isn't CRM Rest Builder supported for Dynamics 365?

**Comment by deepthi261** [comment]
Updated : Unless I open browser in incognito mode & start CRM Rest builder - Its working!
otherwise its not working in both browsers -IE or Chrome

**Comment by jlattimer** [comment]
It is supported - just tried in IE on 8.2.1.207 and it works as expected. 

Must be some other issue specific to your side - suggest using F12 and checking the console

**Comment by jlattimer** [comment]
If you disable Level Up in Chrome it will also work there

**Comment by anilTeke** [comment]
The same problem is still exist in IE 11, although the problem is not exist in Chrome. It seems loading of the CRM Rest Builder will be last life-long on IE side.
