### ISSUE TITLE
How to setup this code ?

### ISSUE THREAD

**Issue by elkhawajah** [jlattimer/CRMRESTBuilder#26]
Hi - I opened the solution, and run it, it opened in browser but there are missing (404 errors) files in console.

![image](https://user-images.githubusercontent.com/1621715/27954400-d55c73de-6320-11e7-8f1f-23b5aabbd5a6.png)

**Comment by jlattimer** [comment]
You install the latest 1.x or 2.x solution from here: https://github.com/jlattimer/CRMRESTBuilder/releases
