### ISSUE TITLE
list.query doesn't contain FetchXML from dynamic Marketing Lists

### ISSUE THREAD

**Issue by cparker4486** [jlattimer/CRMRESTBuilder#29]
Not sure if this is an issue with CRM REST Builder or not but here's what I'm experiencing. I have 2.5.0.0 installed.

When I query 'list', the 'query' property contains a long string of numbers, one or more GUIDs, or numbers and GUIDs. Here are some samples:

    query:"100000018100000025100000007100000040",
    query:"100000005100000013100000014100000041100000016100000026100000033100000039",
    query:"{3E5828B2-0BBE-E411-8A24-A45D36FCBFF8}{361B5EEC-27E1-DF11-9EF9-001E0B46D40C}100000019100000031100000032",

I am trying to create a Logic App so I went ahead and tried doing the same query there and it worked. The returned JSON payload has the expected FetchXML in the 'query' property.

**Comment by jlattimer** [comment]
Fixed
