### ISSUE TITLE
Support of Xrm.WebApi OOB namespace in version for v9.0

### ISSUE THREAD

**Issue by a33ik** [jlattimer/CRMRESTBuilder#30]
Jason,
Would be great if you can add support of Xrm.WebApi namespace for v9.0 version.
Check start of description - https://butenko.pro/2017/10/05/microsoft-dynamics-365-v9-0-usage-of-new-oob-webapi-functions-part-1/
Andrew

**Comment by jlattimer** [comment]
I’ll try and get a quick update out to address this soon.

**Comment by rajyraman** [comment]
I am excited about this feature as well. 😀

**Comment by jlattimer** [comment]
It'll be there when I can get a chance to rebuild a Web API only version

**Comment by jlattimer** [comment]
Added
