### ISSUE TITLE
Not Supported for new update of Dynamics 365 

### ISSUE THREAD

**Issue by deepakgaur111** [jlattimer/CRMRESTBuilder#33]
While importing solution to Dynamics 365 Online Version 1612 (9.0.0.2072) (DB 9.0.0.1103), getting bellow error 

> The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

**Comment by aappddeevv** [comment]
I imported fine under the latest update.

**Comment by jlattimer** [comment]
Make sure you install the solution and not the source code
