### ISSUE TITLE
error after install REST on CRM 2011

### ISSUE THREAD

**Issue by amahroos** [jlattimer/CRMRESTBuilder#35]
I installed the package and after installing and publishing, there's an error as you can see in the attachment.

Thanks for your support,
Ahmed Mahrous
![picture22](https://user-images.githubusercontent.com/33202049/32145886-4bc50908-bcd8-11e7-8304-28bf13e3e9bb.png)

**Comment by jlattimer** [comment]
Try using a FQDN
