### ISSUE TITLE
Bug when an attribute named adx_value is selected

### ISSUE THREAD

**Issue by partridgetim** [jlattimer/CRMRESTBuilder#36]
I'm using [xRM Portal Community Edition](https://github.com/Adoxio/xRM-Portals-Community-Edition) which comes with an entity named adx_contentsnippet that has a field named adx_value. I would like to retrieve one of the records by name. When I build a rest query, clicking the Create Request generates an error. I can see that the field variable incorrectly has the value "dx" because the preceeding if-statement evaluates to true and the substring function strips the first char and the last 6. I'm not sure why that logic is there but I guess the if-condition needs to be more fine grained so as to not evaluate to true in this case.

![image](https://user-images.githubusercontent.com/3292237/32517790-78bdd152-c3d5-11e7-82c3-2d3672ed4758.png)

`Xrm.RESTBuilder.js:3590 Uncaught TypeError: Cannot read property 'AttributeType' of undefined`

![image](https://user-images.githubusercontent.com/3292237/32547972-fe18d6c2-c451-11e7-8bc5-e77f9c93b791.png)

**Comment by jlattimer** [comment]
Fixed
