### ISSUE TITLE
CSDL Not Loading after install

### ISSUE THREAD

**Issue by kschepperly** [jlattimer/CRMRESTBuilder#37]
I just installed V. 2.5.0.0 on Microsoft Dynamics 365 Version 1612 (8.2.1.342). After opening the CRM Rest Builder, it hangs on loading of the CSDL file. The message remains stuck on "Please Wait....". I let it sit for over an hour but it never progresses. I have tried this several times and even rebooted in between.

**Comment by jlattimer** [comment]
Have you tried a different browser? If you open the console (F12) do you see any errors?

**Comment by kschepperly** [comment]
That fixed it. I was using IE11, and also tried in compatibility mode (IE10). Once I tried in Chrome and Edge it loaded immediately. My issue is solved for now, but I will debug in IE and let you know if I find any errors in the console.
