### ISSUE TITLE
Please make v2.5 latest release

### ISSUE THREAD

**Issue by rajyraman** [jlattimer/CRMRESTBuilder#38]
Hitting https://github.com/jlattimer/CRMRESTBuilder/releases/latest returns v1.5 as latest.

**Comment by jlattimer** [comment]
Yeah - I think GitHub automatically flags that based on the date/time uploaded. The 1.x versions are for 2011/2013 and 2.x versions or for 2015+ - I ended up uploading the 1.x version last - so it shows up as latest. Technically speaking the latest 1.x and 2.x versions are both technically the latest versions.
