### ISSUE TITLE
Bad Request when calling action with EntityReference parameter

### ISSUE THREAD

**Issue by mikkelangaju** [jlattimer/CRMRESTBuilder#39]
When generating the code to execute an action with EntityReference (for e.g. the Incident entity) parameters the REST Builder will generate:
incident.primarykeyid = "00000000-0000-0000-0000-000000000000";
incident["@odata.type"] = "Microsoft.Dynamics.CRM.msdyn_incidenttype";
parameters.Incident= incident;

This will cause a "bad request" error with message: "The property 'primarykeyid' does not exist on type 'Microsoft.Dynamics.CRM.msdyn_incidenttype'. Make sure to only use property names that are defined by the type."

Manually changing this to "incident.msdyn_incidenttypeid = "00000000-0000-0000-0000-000000000000";" will work, but is it possible to have this done automatically from the builder, or at least add a warning that it needs to be done.

Full contents of responseText below:
responseText : "{\r\n \"error\":{\r\n \"code\":\"\",\"message\":\"The property 'primarykeyid' does not exist on type 'Microsoft.Dynamics.CRM.msdyn_incidenttype'. Make sure to only use property names that are defined by the type.\",\"innererror\":{\r\n \"message\":\"The property 'primarykeyid' does not exist on type 'Microsoft.Dynamics.CRM.msdyn_incidenttype'. Make sure to only use property names that are defined by the type.\",\"type\":\"Microsoft.Crm.CrmHttpException\",\"stacktrace\":\" at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.ValidateInputParameters(ModelStateDictionary controllerModelState)\\r\\n at Microsoft.Crm.Extensibility.OData.ActionController.PostUnboundAction(String operationName, ODataUntypedActionParameters parameters)\\r\\n at lambda_method(Closure , Object , Object[] )\\r\\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\"\r\n }\r\n }\r\n}"

**Comment by jlattimer** [comment]
Fixed
