### ISSUE TITLE
Worked initially, now Create Request button does nothing

### ISSUE THREAD

**Issue by jrichview** [jlattimer/CRMRESTBuilder#41]
Trying to retrieve 2 attrs from a single entity of type "adx_name".  Fill out the form and click the button and nothing happens anymore.  This is Dynamics 365 (online).
![capture](https://user-images.githubusercontent.com/2236908/37472509-a629937a-2842-11e8-86a9-3eea4616a5ac.JPG)

**Comment by TigerJ** [comment]
I have this issue when using certain browser extensions. try turning off ad blockers and other 3rd party browser utlilities
