### ISSUE TITLE
Please wait since around 30 minutes

### ISSUE THREAD

**Issue by SkippingAdi** [jlattimer/CRMRESTBuilder#50]
Hi all
I just downloaded CRMRestBuilder and imported it successfully into CRM 2016 onPrem (8.0.1.79). After clicking on CRM Rest Builder button a new Window opens, is in disabled state and a message shows "Please wait…", now for about 30 minutes.

Any tips?
Regards
SkippingAdi

**Comment by jlattimer** [comment]
Closed due to lack of response
