### ISSUE TITLE
Error: propertyValue (System.Uri) should be EdmEntityObjectCollection

### ISSUE THREAD

**Issue by MCas86** [jlattimer/CRMRESTBuilder#51]
I'm attempting to associate using the teammember_association relationship. The Disassociation works fine but regardless of whether or not I reverse the order of the entities in the data and the url, the association won't go through.

`			//var dataTeams = { "@odata.id": baseUrl + "/systemusers(" + userid +")" };
			var dataTeams = { "@odata.id": baseUrl + "/teams(" + $(this).attr('id') +")" };
			jQuery.ajax({
				type: "POST",
				//url: baseUrl + "/teams(" + $(this).attr('id') + ")/teammembership_association/$ref",
				url: baseUrl + "/systemusers(" + userid + ")/teammembership_association/$ref",
				data: JSON.stringify(dataTeams),
				contentType: "application/json",
				dataType: "json",
				async: true,
				success: function (response) {
					//success
				},
				error: function (xhr, ajaxOptions, thrownError) {
					//error
				}
			});`

**Comment by kip-dk** [comment]
I do not think you can use the normal associate pattern for team relating users to team, you have to use an action to do that..

This link is showing how:

https://msdn.microsoft.com/da-dk/library/mt607496.aspx

**Comment by MCas86** [comment]
That was it, thank you.
