### ISSUE TITLE
Please use the updated library to show alert

### ISSUE THREAD

**Issue by andz88** [jlattimer/CRMRESTBuilder#53]
currently in the generated code it is still referring to Xrm.Utility.alertDialog("error") when handling the error message. The Xrm.Utility.alertDialog function is marked as deprecated based on this article: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/xrm-utility
Recommendation is to use Xrm.Navigation.openAlertDialog()

**Comment by jlattimer** [comment]
Fixed
