### ISSUE TITLE
Picklist Filters are not generated correctly

### ISSUE THREAD

**Issue by ctophers** [jlattimer/CRMRESTBuilder#54]
The web api generated code for retrieveMultiple Request is not correct.

"fieldLookup" eq "Approved" will result to: 
"fieldLookup eq eq"

**Comment by chaffee007** [comment]
Same issue here.

**Comment by MaxineHarwood** [comment]
same issue here

**Comment by allandecastro** [comment]
Example :
![image](https://user-images.githubusercontent.com/9749002/59859468-05dbd980-937d-11e9-86e7-67fcaec5f7c9.png)

**Comment by mohsinonxrm** [comment]
@jlattimer , fixed in PR #76 , please review.
