### ISSUE TITLE
Associate Role to SystemUser

### ISSUE THREAD

**Issue by AviKumarRaj** [jlattimer/CRMRESTBuilder#55]
Hi Jason, 
Thanks for the awesome tool. I am trying to associate a role to systemuser via webapi. 
When i tried to generate script - I am getting this url with undefined. 

Can you please check if this is a valid issue ?

"/api/data/v9.0/systemusers(00000000-0000-0000-0000-000000000000)/undefined/$ref",

**Comment by kip-dk** [comment]
You cannot attach roles to users via references, you have to use the appropriate action:

https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/mt607641%28v%3dcrm.8%29

**Comment by AviKumarRaj** [comment]
Got it. Thanks.
