### ISSUE TITLE
CRM Rest Builder  Won't Load

### ISSUE THREAD

**Issue by jocamly** [jlattimer/CRMRESTBuilder#56]
The tool won't open for me for a couple months now. I've recently upgraded from 2.5 --> 2.6 still no lock. I deleted the managed solution and installed 2.6 again, same issue... the tool just tries to load and stays on the Please Wait modal screen.

Do you know why this may be happening? What are some things to look for to begin troubleshooting?

I'm running Dynamics 365 8.2.2.112 On-Prem using https and a hostname.

Thanks,

**Comment by jlattimer** [comment]
Try using a FQDN instead

**Comment by jlattimer** [comment]
No response - closing
