### ISSUE TITLE
Rest Builder Loading Error

### ISSUE THREAD

**Issue by abalhusseini** [jlattimer/CRMRESTBuilder#57]
Hi,

I have CRM 365 version 9.x and when I start the REST builder its show error message and keep loading for a very long time . I did remove the slolution and re install it again.

![capture](https://user-images.githubusercontent.com/44805224/48062920-870ea380-e1d4-11e8-8642-c37930c14bd0.JPG)

**Comment by jlattimer** [comment]
Hit F12 and report back what the error in the console is

**Comment by abalhusseini** [comment]
Anything else you need from my side?
