### ISSUE TITLE
DateTime can't convert to ISO

### ISSUE THREAD

**Issue by DarkBlues** [jlattimer/CRMRESTBuilder#59]
Hi,
Thank you for your useful tool.It gave me a great help.But recently I find it can't build ODate when I select an attribute with type of DateTime .

![default](https://user-images.githubusercontent.com/20699070/48590785-da72b580-e97b-11e8-866c-ba0e73abc73a.PNG)
![2](https://user-images.githubusercontent.com/20699070/48590790-dfd00000-e97b-11e8-9cdf-c4dd21b1f548.PNG)

**Comment by seefernando** [comment]
Hey Jason,

I'm facing a out of range issue as well related to time.  I'm not sure if its related to this bug, I can create a new issue if you'd like.

When I use a date (createdon) as a filter the request is never created and the console logs a CrashReport.

![image](https://user-images.githubusercontent.com/6138858/64204280-7023f680-ce63-11e9-9bd4-f6cfce9a596b.png)

I tried past dates and times, future dates and times and no times.

Thanks again for an awesome tool!


`global.ashx?ver=-558401387:6870 CrashReport:
		FileName://WebResources/lat_/CRMRESTBuilder/scripts/Xrm.RESTBuilder.js
		LineNumber:4683
		Function:
		ErrorReport:<CrmScriptErrorReport>
  <ReportVersion>1.0</ReportVersion>
   <OriginContext></OriginContext>
   <OriginCorrelationId>undefined</OriginCorrelationId>
  <ScriptErrorDetails>
   <Message>Uncaught RangeError&#58; Invalid time value</Message>
   <Line>4683</Line>
   <URL>&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;Xrm.RESTBuilder.js&#63;ver&#61;0</URL>
   <PageURL>&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;Xrm.RESTBuilder.htm&#63;pagemode&#61;iframe</PageURL>
   <Function></Function>
   <FunctionRaw></FunctionRaw>
   <SourceScriptName></SourceScriptName>
   <CallStack>
RangeError&#58; Invalid time value&#10;    at Date.toISOString &#40;&#60;anonymous&#62;&#41;&#10;    at Object.Xrm.RESTBuilder.BuildFilterString_WebApi &#40;https&#58;&#47;&#47;mycrminstance.crm3.dynamics.com&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;Xrm.RESTBuilder.js&#58;4683&#58;146&#41;&#10;    at Object.Xrm.RESTBuilder.CreateUrl &#40;https&#58;&#47;&#47;mycrminstance.crm3.dynamics.com&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;Xrm.RESTBuilder.js&#58;3415&#58;64&#41;&#10;    at Object.Xrm.RESTBuilder.RetrieveMultiple &#40;https&#58;&#47;&#47;mycrminstance.crm3.dynamics.com&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;Xrm.RESTBuilder.js&#58;3347&#58;18&#41;&#10;    at HTMLAnchorElement.Xrm.RESTBuilder.CreateRequest_Click &#40;https&#58;&#47;&#47;mycrminstance.crm3.dynamics.com&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;Xrm.RESTBuilder.js&#58;5861&#58;20&#41;&#10;    at HTMLAnchorElement.dispatch &#40;https&#58;&#47;&#47;mycrminstance.crm3.dynamics.com&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;jquery1.9.1.min.js&#58;2&#58;28337&#41;&#10;    at HTMLAnchorElement.v.handle &#40;https&#58;&#47;&#47;mycrminstance.crm3.dynamics.com&#47;&#47;WebResources&#47;lat_&#47;CRMRESTBuilder&#47;scripts&#47;jquery1.9.1.min.js&#58;2&#58;25042&#41;   </CallStack>
  </ScriptErrorDetails>
  <ClientInformation>
   <BrowserUserAgent>Mozilla&#47;5.0 &#40;Windows NT 10.0&#59; Win64&#59; x64&#41; AppleWebKit&#47;537.36 &#40;KHTML, like Gecko&#41; Chrome&#47;76.0.3809.132 Safari&#47;537.36</BrowserUserAgent>
   <BrowserLanguage>undefined</BrowserLanguage>
   <SystemLanguage>undefined</SystemLanguage>
   <UserLanguage>undefined</UserLanguage>
   <ScreenResolution>3440x1440</ScreenResolution>
   <ClientName>Web</ClientName>
   <ClienState>Online</ClienState>
   <ClientTime>2019-09-03T15&#58;45&#58;30</ClientTime>
  </ClientInformation>
</CrmScriptErrorReport>`

**Comment by jlattimer** [comment]
Fixed
