### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by waqas-idrees-confiz** [jlattimer/CRMRESTBuilder#6]
I download the project, open the solution, enable directory browsing run the web site. 

Just see the following page what will be the issue. Please help me
![image](https://cloud.githubusercontent.com/assets/7046064/21068721/a111c708-be95-11e6-985c-8f1f84da44ed.png)

**Comment by jlattimer** [comment]
You need to install the v2.5.0.0 solution file under releases into CRM (not under the website folder).
https://github.com/jlattimer/CRMRESTBuilder/releases
Settings -> Solutions -> Import
