### ISSUE TITLE
Xrm.WebApi 9.1 ExecuteWorkflow Action

### ISSUE THREAD

**Issue by jeffrey0404** [jlattimer/CRMRESTBuilder#60]
I'm receiving an issue with the ExecuteWorkflow Action when output is Xrm.WebApi. Everything works fine when using  XMLHTTP.
![setup](https://user-images.githubusercontent.com/45215053/48804518-76812180-ecda-11e8-9bc3-bf22ec5d2a18.PNG)
![query](https://user-images.githubusercontent.com/45215053/48804532-7f71f300-ecda-11e8-87a3-ad81226b23d6.PNG)
![error](https://user-images.githubusercontent.com/45215053/48804545-839e1080-ecda-11e8-8be3-a7602cd47961.PNG)

**Comment by JamesStuder** [comment]
I am having this same issue.  Where you able to find a solution?

**Comment by JamesStuder** [comment]
I tried to move to using XMLHTTP and it isn't working either.  I made no code changes, except for the GUIDs.

**Comment by jeffrey0404** [comment]
I ended up using XMLHttpRequest (async) like the following. blnWebResource is a flag we use to designate if we are calling from a web resource like an HTML page.

//Execute A Workflow
function executeWorkflow(szWorkflowID, recordId, blnWebResource) {
    try {
        var parameters = {};
        parameters.EntityId = recordId;

        var req = new XMLHttpRequest();
        req.open("POST", Xrm.Utility.getGlobalContext().getClientUrl() + "/api/data/v9.0/workflows(" + szWorkflowID + ")/Microsoft.Dynamics.CRM.ExecuteWorkflow", true);
        req.setRequestHeader("OData-MaxVersion", "4.0");
        req.setRequestHeader("OData-Version", "4.0");
        req.setRequestHeader("Accept", "application/json");
        req.setRequestHeader("Content-Type", "application/json; charset=utf-8");
        req.onreadystatechange = function() {
            if (this.readyState === 4) {
                debugger;
                req.onreadystatechange = null;
                if (this.status === 204 || this.status === 200 || this.statusText.toUpperCase() === "OK") {
                    //var results = JSON.parse(this.response);
                    if (blnWebResource === true) {
                        parent.Xrm.Page.data.save();
                        parent.Xrm.Page.data.refresh();
                    } else {
                        Xrm.Page.data.save();
                        Xrm.Page.data.refresh();
                    }
                } else {
                    alert(this.statusText, blnWebResource);
                }
            }
        };
        req.send(JSON.stringify(parameters));
    } catch (e) {
        alert("Error in executeWorkflow: " + e.message, blnWebResource);
    }
}

function alert(message, blnWebResource) {
    var alertStrings = { confirmButtonLabel: "Close", text: message };
    var alertOptions = { height: 180, width: 300 };
    if (blnWebResource) {
        parent.Xrm.Navigation.openAlertDialog(alertStrings, alertOptions);
    }
    else {
        Xrm.Navigation.openAlertDialog(alertStrings, alertOptions);
    }
}

Hope this helps.

**Comment by JamesStuder** [comment]
I got is to work with Xrm.WebApi.  The issue is in the object that get's created as parameters and entity.  I removed that and replaced.  Here is the code that I used to get it working.

`var executeWorkflowRequest =
                {
                    entity: { id: workflowid, entityType: "workflow" },
                    EntityId: { guid: entityID },

                    getMetadata: function ()
                    {
                        return {
                            boundParameter: "entity",
                            parameterTypes: {
                                "entity": {
                                    "typeName": "mscrm.workflow",
                                    "structuralProperty": 5
                                },
                                "EntityId": {
                                    "typeName": "Edm.Guid",
                                    "structuralProperty": 1
                                }
                            },
                            operationType: 0,
                            operationName: "ExecuteWorkflow"
                        };
                    }
                };  

                Xrm.WebApi.online.execute(executeWorkflowRequest).then(
                    function success(result)
                    {
                        if (result.ok)
                        {
                            var results = JSON.parse(result.responseText);
                            alert(results);
                        }
                    },
                    function (error)
                    {
                        Xrm.Utility.alertDialog(error.message);
                    }
                );`

The main change is to remove the object and add this code: 
`                    entity: { id: workflowid, entityType: "workflow" },
                    EntityId: { guid: entityID },`

replace workflowid with the guid of the workflow and entityID with the record that you want it to run against.

**Comment by jlattimer** [comment]
Fixed
