### ISSUE TITLE
WebAPI RetrieveMultiple Call statecode and statuscode query have eq eq in result

### ISSUE THREAD

**Issue by ADPerkin** [jlattimer/CRMRESTBuilder#61]
Hi Jason,

When I create a simple Retrieve Multiple Web API call on the Incident entity and add StateCode and StatusCode then try and filter on StateCode equal Active the generated code fails with a Bad Request.

I noted that this line is incorrect as it has eq eq instead of eq 0:

req.open("GET", Xrm.Page.context.getClientUrl() + "/api/data/v8.2/incidents?$select=statecode,statuscode&$filter=statecode eq eq", true);

This seems to be specific to this version as 2.5.0.0 was fine. Editing the code manually means it executes fine.

**Comment by emregulcan** [comment]
I think this is same with issue #54

**Comment by mohsinonxrm** [comment]
@jlattimer , fixed in PR #76 , please review.

**Comment by ADPerkin** [comment]
Thanks for sorting that one - on hols at present but love this utility and that’s one of the few issues I ever had sorted - thanks again
Andrew
    	
    	

    	Andrew Perkin
    
  




On Wed, Nov 6, 2019 at 7:33 PM +0000, "Jason Lattimer" <notifications@github.com> wrote:












Closed #61.
