### ISSUE TITLE
the tool doesn't load at all

### ISSUE THREAD

**Issue by sdnd2000** [jlattimer/CRMRESTBuilder#63]
I'm running Dynamics 365 8.2.1 On-Prem.

I've recently upgraded from 2.5 --> 2.6 still no lock. I deleted the managed solution and installed 2.6 again, same issue... the tool just tries to load and stays on the Please Wait modal screen.

**Comment by jlattimer** [comment]
Close do to lack of response

**Comment by alrekr** [comment]
I had the same problem. I was using the server name to access Dynamics. After changing to FQDN the solution loaded in a few seconds.
