### ISSUE TITLE
status code and state code inserting eq not 0,1,2

### ISSUE THREAD

**Issue by JamesStuder** [jlattimer/CRMRESTBuilder#66]
Trying to get specific workflow by name.  I added what was needed in CRM Rest builder.  I then added state code and status code to make sure I get activated only.  When it generates the url it does statuscode eq eq&statecode eq eq.  This was under the retrieve mulitple, web api, v9.1.

**Comment by RomanVdV** [comment]
Same on OnPremise 8.2.3

**Comment by NeilN1** [comment]
Yes, any chance of a fix?

**Comment by phyle** [comment]
It appears to be the same for all OptionSet/Picklist fields with version 2.6.0.0 regardless of the Web API endpoint version.

**Comment by jlattimer** [comment]
#61 #54

**Comment by mohsinonxrm** [comment]
@jlattimer , fixed in PR #76 , please review.
