### ISSUE TITLE
Status 500: System.ServiceModel.ServiceActivationException

### ISSUE THREAD

**Issue by VenkattaPidikiti** [jlattimer/CRMRESTBuilder#67]
Hello,
I have installed REST Builder at On-premise (Dynamics 365 CE 9.0) environments and it is working fine at Dev and I am getting pop up with below message at Test environment and continually loading with the caption"Please wait"
Status 500: System.ServiceModel.ServiceActivationException
![RESTBuilder-1](https://user-images.githubusercontent.com/11817148/54817819-d229de80-4cbd-11e9-8a7b-73044f927174.jpg)
![RESTBuilder-2](https://user-images.githubusercontent.com/11817148/54817830-d950ec80-4cbd-11e9-8433-1523c444ff80.jpg)

**Comment by jlattimer** [comment]
If you hit F12 and switch to the console tab, is there error detail?

**Comment by VenkattaPidikiti** [comment]
Hello, attached console tab screenshot for error details
![CRMRestbuilder_err](https://user-images.githubusercontent.com/11817148/54898476-80b66500-4ef2-11e9-9803-7fcadb50cfe4.jpg)

**Comment by VenkattaPidikiti** [comment]
Hello ,
Sorry for delay response. The issue was resolved and it was born from IIS settings not from Product.
Venkatta.

**Comment by NeilN1** [comment]
Hi @VenkattaPidikiti - do you mind sharing how you solved this? We have the same issue with one of our servers.
