### ISSUE TITLE
msdyn_SetTeamsDocumentStatus not available in Primary Entity List

### ISSUE THREAD

**Issue by iannicholls** [jlattimer/CRMRESTBuilder#70]
I've added the MS teams functionality and want to create a REST statement to add custom entities but it doesn't appear in the list of msdyn options.

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/integration-dev/teams-integration-using-code

**Comment by jlattimer** [comment]
This is an Action so it wouldn't appear under the entity list for Create

![image](https://user-images.githubusercontent.com/1769982/62792050-0ac32c80-ba94-11e9-94e3-0d416e2bb407.png)

**Comment by iannicholls** [comment]
Thanks for this quick info, at least the code I have seems correct, it just give a 400 bad request all the time though. Has this ever worked for you?

**Comment by jlattimer** [comment]
Based on the metadata which build the parameters, LogicalEntityNames is a string, however looking at the documentation in the link it appears that you need to send the string in the form of an array. At least for the JS code you'd need to manually change the output to look like this:

```javascript
parameters.LogicalEntityNames = "[\"account\"]";
```
