### ISSUE TITLE
RetrieveSharedPrincipalsAndAccess with Xrm.WebApi.online.execute is not working.

### ISSUE THREAD

**Issue by anandmyadam** [jlattimer/CRMRESTBuilder#71]
RetrieveSharedPrincipalsAndAccess with Xrm.WebApi.online.execute is not working.
I tried using current online trial instance version "9.1.0000.8018"

Error message:
message: "Resource not found for the segment 'RetrieveSharedPrincipalsAndAccess'."
stacktrace: "   at Microsoft.OData.UriParser.ODataPathParser.CreateDynamicPathSegment(ODataPathSegment previous, String identifier, String parenthesisExpression)
↵   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)
↵   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)
↵   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)
↵   at Microsoft.OData.UriParser.ODataUriParser.Initialize()
↵   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer, Boolean template)
↵   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)
↵   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)"

**Comment by jlattimer** [comment]
Is working now - generates this code:

```javascript
var parameters = {};
var target = {};
target.accountid = "C7E5EB35-CC67-E911-A816-000D3A3B5933"; //Delete if creating new record 
target["@odata.type"] = "Microsoft.Dynamics.CRM.account";
parameters.Target = target;

var retrieveSharedPrincipalsAndAccessRequest = {
    Target: parameters.Target,

    getMetadata: function() {
        return {
            boundParameter: null,
            parameterTypes: {
                "Target": {
                    "typeName": "mscrm.crmbaseentity",
                    "structuralProperty": 5
                }
            },
            operationType: 1,
            operationName: "RetrieveSharedPrincipalsAndAccess"
        };
    }
};

Xrm.WebApi.online.execute(retrieveSharedPrincipalsAndAccessRequest).then(
    function success(result) {
        if (result.ok) {
            var results = JSON.parse(result.responseText);
        }
    },
    function(error) {
        Xrm.Navigation.openAlertDialog({
            confirmButtonLabel: "OK",
            text: error.message,
            title: "Error"
        });
    }
);
```
