### ISSUE TITLE
How to launch it 

### ISSUE THREAD

**Issue by Mracobes9** [jlattimer/CRMRESTBuilder#72]
Hi. How can i launch it ? I download release solution, but i have not idea what i can do next

**Comment by jlattimer** [comment]
Import the solution: [ https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/customize/import-update-upgrade-solution](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/customize/import-update-upgrade-solution)
