### ISSUE TITLE
Activity Regarding Object and Custom Lookup field

### ISSUE THREAD

**Issue by AndersHybridPro** [jlattimer/CRMRESTBuilder#73]
First off, thanks for a fantastic time saving tool! 
Writing this to make it even better. Version v2.6.0.0
9.1 Web Api Output XMLHttp

We have a custom activity, and trying to set Regarding object and a custom lookup field named "hpro_batch". 
The result from the tool:
var entity = {};
entity["hpro_batch@odata.bind"] = "/hpro_batchs(34234)";
entity["regardingobjectid@odata.bind"] = "/contacts(234)";

Gave "entityRelationshipRole for given navigation property not found"

What works is to replace the attribute names with:
hpro_batch_hpro_sms (hpro_batch_hpro_sms@odata.bind)
regardingobjectid_contact (regardingobjectid_contact@odata.bind)

Workaround: Set a custom lookup by navigating to the OData metadata and find the corresponding navigation property and use that as the attribute name:
<NavigationProperty Name="hpro_batch_hpro_sms" Type="mscrm.hpro_batch" Nullable="false" Partner="hpro_hpro_batch_hpro_sms_batch">
          <ReferentialConstraint Property="_hpro_batch_value" ReferencedProperty="hpro_batchid" />
        </NavigationProperty>

Best regards,
Anders

**Comment by jlattimer** [comment]
Should be fixed in next release.
