### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by pab74** [jlattimer/CRMRESTBuilder#8]
Hello! Great job!! Thank you very much. I have just installed the latest version 2.5 on a CRM 2016  (8.1.0.359) and when I run rest builder, its stuck on Please wait... and small icon with Loading CSDL... 
I have tried with 2.4 but no luck, same issue. What could it be?
Thank you

**Comment by jlattimer** [comment]
What browser are you using and have you tried a different one?

**Comment by pab74** [comment]
IE 11.0.9600
No, I don't have another browser to test. this machine is the CRM Server
itself, (Win server 2012 R2)

2016-12-29 17:34 GMT+01:00 Jason Lattimer <notifications@github.com>:

**Comment by jlattimer** [comment]
Are you using localhost to access? Can you try the FQDN?

**Comment by pab74** [comment]
Hi, I don't use localhost. I use already the FQDN :-(

2016-12-29 18:01 GMT+01:00 Jason Lattimer <notifications@github.com>:

**Comment by jlattimer** [comment]
Not totally sure then. I hate to say it but I'm inclined to think it's an issue on your end as many others use IE without an problems. I have heard or some things not working when running on the server directly but most of them were using localhost which seemed to cause some of web resources not to load correctly.

**Comment by bdbvb** [comment]
I think I'm having a similar issue,, and it only started happening with a recent update. It looks like the endpoint is defaulted to 2011, and maybe it's trying to hit an endpoint that doesn't exist, and just times out, leaving the progress indicator in the way. I'm on CRM 2016 (web api 8.1). I'm using Chrome. I'm not accessing directly on the server.

![image](https://cloud.githubusercontent.com/assets/11095196/23139295/b7f334f8-f779-11e6-8f3f-465262883b22.png)

**Comment by pab74** [comment]
On my side the problem seems solved..i think it was related to
Compatibility view on IE, but not sure... and if you are facing the problem
with Chrome probably it is another issue.
Good luck

2017-02-20 20:35 GMT+01:00 bdbvb <notifications@github.com>:
