### ISSUE TITLE
"Internal Server Error" when setting multi-line text field

### ISSUE THREAD

**Issue by mizzou626** [jlattimer/CRMRESTBuilder#9]
Anytime I try to set a memo field I get an error when trying to create a record. This happens in Chrome and IE. The detail within the error says  "This is the Create function: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)." Here is a screenshot of my request:

![image](https://cloud.githubusercontent.com/assets/25042938/21827164/48244c66-d73f-11e6-872e-7271bec8a010.png)

**Comment by jlattimer** [comment]
Do you have plug-ins firing on create of this entity type? Error detail including the text "This is the Create function" doesn't sound like something generated by the system. 

Can you create other record types?

**Comment by mizzou626** [comment]
I just ran the exact same code again and didn’t receive an error this time. I’m going to blame this on CRM Online. There were plugins registered on the create message which haven’t been changed. Unfortunately, I wasn’t able to test a different entity before it started working.

**Comment by jlattimer** [comment]
Fair enough - closing this out for now
